export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 18,
    FONT_SIZE_LARGE: 22,
    PRIMARY_COLOR: '#78b7bb',
    SECONDARY_COLOR: '#FFF0C3',
    LIGHT_COLOR: '#FBFBFB',
    ORANGE_COLOR: '#FEDEC3',
    DARK_COLOR: '#808B97',
    DARK_HOVER_COLOR: '#48525D',
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '400',
    FONT_WEIGHT_HEAVY: '800'
  };